// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Book.proto

package com.grpc.common;

public final class BookOuterClass {
  private BookOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.common.Book)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.grpc.common.BookId id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>.com.grpc.common.BookId id = 1;</code>
     */
    com.grpc.common.BookOuterClass.BookId getId();
    /**
     * <code>.com.grpc.common.BookId id = 1;</code>
     */
    com.grpc.common.BookOuterClass.BookIdOrBuilder getIdOrBuilder();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 pageCount = 3;</code>
     */
    int getPageCount();

    /**
     * <code>.com.grpc.common.Author author = 4;</code>
     */
    boolean hasAuthor();
    /**
     * <code>.com.grpc.common.Author author = 4;</code>
     */
    com.grpc.common.AuthorOuterClass.Author getAuthor();
    /**
     * <code>.com.grpc.common.Author author = 4;</code>
     */
    com.grpc.common.AuthorOuterClass.AuthorOrBuilder getAuthorOrBuilder();
  }
  /**
   * Protobuf type {@code com.grpc.common.Book}
   */
  public  static final class Book extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.common.Book)
      BookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Book.newBuilder() to construct.
    private Book(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Book() {
      name_ = "";
      pageCount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Book(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.grpc.common.BookOuterClass.BookId.Builder subBuilder = null;
              if (id_ != null) {
                subBuilder = id_.toBuilder();
              }
              id_ = input.readMessage(com.grpc.common.BookOuterClass.BookId.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(id_);
                id_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              pageCount_ = input.readInt32();
              break;
            }
            case 34: {
              com.grpc.common.AuthorOuterClass.Author.Builder subBuilder = null;
              if (author_ != null) {
                subBuilder = author_.toBuilder();
              }
              author_ = input.readMessage(com.grpc.common.AuthorOuterClass.Author.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(author_);
                author_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_Book_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_Book_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.common.BookOuterClass.Book.class, com.grpc.common.BookOuterClass.Book.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private com.grpc.common.BookOuterClass.BookId id_;
    /**
     * <code>.com.grpc.common.BookId id = 1;</code>
     */
    public boolean hasId() {
      return id_ != null;
    }
    /**
     * <code>.com.grpc.common.BookId id = 1;</code>
     */
    public com.grpc.common.BookOuterClass.BookId getId() {
      return id_ == null ? com.grpc.common.BookOuterClass.BookId.getDefaultInstance() : id_;
    }
    /**
     * <code>.com.grpc.common.BookId id = 1;</code>
     */
    public com.grpc.common.BookOuterClass.BookIdOrBuilder getIdOrBuilder() {
      return getId();
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGECOUNT_FIELD_NUMBER = 3;
    private int pageCount_;
    /**
     * <code>int32 pageCount = 3;</code>
     */
    public int getPageCount() {
      return pageCount_;
    }

    public static final int AUTHOR_FIELD_NUMBER = 4;
    private com.grpc.common.AuthorOuterClass.Author author_;
    /**
     * <code>.com.grpc.common.Author author = 4;</code>
     */
    public boolean hasAuthor() {
      return author_ != null;
    }
    /**
     * <code>.com.grpc.common.Author author = 4;</code>
     */
    public com.grpc.common.AuthorOuterClass.Author getAuthor() {
      return author_ == null ? com.grpc.common.AuthorOuterClass.Author.getDefaultInstance() : author_;
    }
    /**
     * <code>.com.grpc.common.Author author = 4;</code>
     */
    public com.grpc.common.AuthorOuterClass.AuthorOrBuilder getAuthorOrBuilder() {
      return getAuthor();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != null) {
        output.writeMessage(1, getId());
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (pageCount_ != 0) {
        output.writeInt32(3, pageCount_);
      }
      if (author_ != null) {
        output.writeMessage(4, getAuthor());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getId());
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (pageCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pageCount_);
      }
      if (author_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAuthor());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.common.BookOuterClass.Book)) {
        return super.equals(obj);
      }
      com.grpc.common.BookOuterClass.Book other = (com.grpc.common.BookOuterClass.Book) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && getName()
          .equals(other.getName());
      result = result && (getPageCount()
          == other.getPageCount());
      result = result && (hasAuthor() == other.hasAuthor());
      if (hasAuthor()) {
        result = result && getAuthor()
            .equals(other.getAuthor());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PAGECOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getPageCount();
      if (hasAuthor()) {
        hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
        hash = (53 * hash) + getAuthor().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.common.BookOuterClass.Book parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.common.BookOuterClass.Book parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.common.BookOuterClass.Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.common.BookOuterClass.Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.common.BookOuterClass.Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.common.BookOuterClass.Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.common.BookOuterClass.Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.common.BookOuterClass.Book prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.common.Book}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.common.Book)
        com.grpc.common.BookOuterClass.BookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_Book_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_Book_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.common.BookOuterClass.Book.class, com.grpc.common.BookOuterClass.Book.Builder.class);
      }

      // Construct using com.grpc.common.BookOuterClass.Book.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (idBuilder_ == null) {
          id_ = null;
        } else {
          id_ = null;
          idBuilder_ = null;
        }
        name_ = "";

        pageCount_ = 0;

        if (authorBuilder_ == null) {
          author_ = null;
        } else {
          author_ = null;
          authorBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_Book_descriptor;
      }

      @java.lang.Override
      public com.grpc.common.BookOuterClass.Book getDefaultInstanceForType() {
        return com.grpc.common.BookOuterClass.Book.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.common.BookOuterClass.Book build() {
        com.grpc.common.BookOuterClass.Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.common.BookOuterClass.Book buildPartial() {
        com.grpc.common.BookOuterClass.Book result = new com.grpc.common.BookOuterClass.Book(this);
        if (idBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        result.name_ = name_;
        result.pageCount_ = pageCount_;
        if (authorBuilder_ == null) {
          result.author_ = author_;
        } else {
          result.author_ = authorBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.common.BookOuterClass.Book) {
          return mergeFrom((com.grpc.common.BookOuterClass.Book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.common.BookOuterClass.Book other) {
        if (other == com.grpc.common.BookOuterClass.Book.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getPageCount() != 0) {
          setPageCount(other.getPageCount());
        }
        if (other.hasAuthor()) {
          mergeAuthor(other.getAuthor());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.common.BookOuterClass.Book parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.common.BookOuterClass.Book) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.grpc.common.BookOuterClass.BookId id_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.grpc.common.BookOuterClass.BookId, com.grpc.common.BookOuterClass.BookId.Builder, com.grpc.common.BookOuterClass.BookIdOrBuilder> idBuilder_;
      /**
       * <code>.com.grpc.common.BookId id = 1;</code>
       */
      public boolean hasId() {
        return idBuilder_ != null || id_ != null;
      }
      /**
       * <code>.com.grpc.common.BookId id = 1;</code>
       */
      public com.grpc.common.BookOuterClass.BookId getId() {
        if (idBuilder_ == null) {
          return id_ == null ? com.grpc.common.BookOuterClass.BookId.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.grpc.common.BookId id = 1;</code>
       */
      public Builder setId(com.grpc.common.BookOuterClass.BookId value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
          onChanged();
        } else {
          idBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.grpc.common.BookId id = 1;</code>
       */
      public Builder setId(
          com.grpc.common.BookOuterClass.BookId.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
          onChanged();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.grpc.common.BookId id = 1;</code>
       */
      public Builder mergeId(com.grpc.common.BookOuterClass.BookId value) {
        if (idBuilder_ == null) {
          if (id_ != null) {
            id_ =
              com.grpc.common.BookOuterClass.BookId.newBuilder(id_).mergeFrom(value).buildPartial();
          } else {
            id_ = value;
          }
          onChanged();
        } else {
          idBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.grpc.common.BookId id = 1;</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = null;
          onChanged();
        } else {
          id_ = null;
          idBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.grpc.common.BookId id = 1;</code>
       */
      public com.grpc.common.BookOuterClass.BookId.Builder getIdBuilder() {
        
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.grpc.common.BookId id = 1;</code>
       */
      public com.grpc.common.BookOuterClass.BookIdOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              com.grpc.common.BookOuterClass.BookId.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>.com.grpc.common.BookId id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.grpc.common.BookOuterClass.BookId, com.grpc.common.BookOuterClass.BookId.Builder, com.grpc.common.BookOuterClass.BookIdOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.grpc.common.BookOuterClass.BookId, com.grpc.common.BookOuterClass.BookId.Builder, com.grpc.common.BookOuterClass.BookIdOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int pageCount_ ;
      /**
       * <code>int32 pageCount = 3;</code>
       */
      public int getPageCount() {
        return pageCount_;
      }
      /**
       * <code>int32 pageCount = 3;</code>
       */
      public Builder setPageCount(int value) {
        
        pageCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pageCount = 3;</code>
       */
      public Builder clearPageCount() {
        
        pageCount_ = 0;
        onChanged();
        return this;
      }

      private com.grpc.common.AuthorOuterClass.Author author_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.grpc.common.AuthorOuterClass.Author, com.grpc.common.AuthorOuterClass.Author.Builder, com.grpc.common.AuthorOuterClass.AuthorOrBuilder> authorBuilder_;
      /**
       * <code>.com.grpc.common.Author author = 4;</code>
       */
      public boolean hasAuthor() {
        return authorBuilder_ != null || author_ != null;
      }
      /**
       * <code>.com.grpc.common.Author author = 4;</code>
       */
      public com.grpc.common.AuthorOuterClass.Author getAuthor() {
        if (authorBuilder_ == null) {
          return author_ == null ? com.grpc.common.AuthorOuterClass.Author.getDefaultInstance() : author_;
        } else {
          return authorBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.grpc.common.Author author = 4;</code>
       */
      public Builder setAuthor(com.grpc.common.AuthorOuterClass.Author value) {
        if (authorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          author_ = value;
          onChanged();
        } else {
          authorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.grpc.common.Author author = 4;</code>
       */
      public Builder setAuthor(
          com.grpc.common.AuthorOuterClass.Author.Builder builderForValue) {
        if (authorBuilder_ == null) {
          author_ = builderForValue.build();
          onChanged();
        } else {
          authorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.grpc.common.Author author = 4;</code>
       */
      public Builder mergeAuthor(com.grpc.common.AuthorOuterClass.Author value) {
        if (authorBuilder_ == null) {
          if (author_ != null) {
            author_ =
              com.grpc.common.AuthorOuterClass.Author.newBuilder(author_).mergeFrom(value).buildPartial();
          } else {
            author_ = value;
          }
          onChanged();
        } else {
          authorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.grpc.common.Author author = 4;</code>
       */
      public Builder clearAuthor() {
        if (authorBuilder_ == null) {
          author_ = null;
          onChanged();
        } else {
          author_ = null;
          authorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.grpc.common.Author author = 4;</code>
       */
      public com.grpc.common.AuthorOuterClass.Author.Builder getAuthorBuilder() {
        
        onChanged();
        return getAuthorFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.grpc.common.Author author = 4;</code>
       */
      public com.grpc.common.AuthorOuterClass.AuthorOrBuilder getAuthorOrBuilder() {
        if (authorBuilder_ != null) {
          return authorBuilder_.getMessageOrBuilder();
        } else {
          return author_ == null ?
              com.grpc.common.AuthorOuterClass.Author.getDefaultInstance() : author_;
        }
      }
      /**
       * <code>.com.grpc.common.Author author = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.grpc.common.AuthorOuterClass.Author, com.grpc.common.AuthorOuterClass.Author.Builder, com.grpc.common.AuthorOuterClass.AuthorOrBuilder> 
          getAuthorFieldBuilder() {
        if (authorBuilder_ == null) {
          authorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.grpc.common.AuthorOuterClass.Author, com.grpc.common.AuthorOuterClass.Author.Builder, com.grpc.common.AuthorOuterClass.AuthorOrBuilder>(
                  getAuthor(),
                  getParentForChildren(),
                  isClean());
          author_ = null;
        }
        return authorBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.common.Book)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.common.Book)
    private static final com.grpc.common.BookOuterClass.Book DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.common.BookOuterClass.Book();
    }

    public static com.grpc.common.BookOuterClass.Book getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Book>
        PARSER = new com.google.protobuf.AbstractParser<Book>() {
      @java.lang.Override
      public Book parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Book(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Book> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Book> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.common.BookOuterClass.Book getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BooksOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.common.Books)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.grpc.common.Book books = 1;</code>
     */
    java.util.List<com.grpc.common.BookOuterClass.Book> 
        getBooksList();
    /**
     * <code>repeated .com.grpc.common.Book books = 1;</code>
     */
    com.grpc.common.BookOuterClass.Book getBooks(int index);
    /**
     * <code>repeated .com.grpc.common.Book books = 1;</code>
     */
    int getBooksCount();
    /**
     * <code>repeated .com.grpc.common.Book books = 1;</code>
     */
    java.util.List<? extends com.grpc.common.BookOuterClass.BookOrBuilder> 
        getBooksOrBuilderList();
    /**
     * <code>repeated .com.grpc.common.Book books = 1;</code>
     */
    com.grpc.common.BookOuterClass.BookOrBuilder getBooksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.grpc.common.Books}
   */
  public  static final class Books extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.common.Books)
      BooksOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Books.newBuilder() to construct.
    private Books(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Books() {
      books_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Books(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                books_ = new java.util.ArrayList<com.grpc.common.BookOuterClass.Book>();
                mutable_bitField0_ |= 0x00000001;
              }
              books_.add(
                  input.readMessage(com.grpc.common.BookOuterClass.Book.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          books_ = java.util.Collections.unmodifiableList(books_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_Books_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_Books_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.common.BookOuterClass.Books.class, com.grpc.common.BookOuterClass.Books.Builder.class);
    }

    public static final int BOOKS_FIELD_NUMBER = 1;
    private java.util.List<com.grpc.common.BookOuterClass.Book> books_;
    /**
     * <code>repeated .com.grpc.common.Book books = 1;</code>
     */
    public java.util.List<com.grpc.common.BookOuterClass.Book> getBooksList() {
      return books_;
    }
    /**
     * <code>repeated .com.grpc.common.Book books = 1;</code>
     */
    public java.util.List<? extends com.grpc.common.BookOuterClass.BookOrBuilder> 
        getBooksOrBuilderList() {
      return books_;
    }
    /**
     * <code>repeated .com.grpc.common.Book books = 1;</code>
     */
    public int getBooksCount() {
      return books_.size();
    }
    /**
     * <code>repeated .com.grpc.common.Book books = 1;</code>
     */
    public com.grpc.common.BookOuterClass.Book getBooks(int index) {
      return books_.get(index);
    }
    /**
     * <code>repeated .com.grpc.common.Book books = 1;</code>
     */
    public com.grpc.common.BookOuterClass.BookOrBuilder getBooksOrBuilder(
        int index) {
      return books_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < books_.size(); i++) {
        output.writeMessage(1, books_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < books_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, books_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.common.BookOuterClass.Books)) {
        return super.equals(obj);
      }
      com.grpc.common.BookOuterClass.Books other = (com.grpc.common.BookOuterClass.Books) obj;

      boolean result = true;
      result = result && getBooksList()
          .equals(other.getBooksList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBooksCount() > 0) {
        hash = (37 * hash) + BOOKS_FIELD_NUMBER;
        hash = (53 * hash) + getBooksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.common.BookOuterClass.Books parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.common.BookOuterClass.Books parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.Books parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.common.BookOuterClass.Books parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.Books parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.common.BookOuterClass.Books parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.Books parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.common.BookOuterClass.Books parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.Books parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.common.BookOuterClass.Books parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.Books parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.common.BookOuterClass.Books parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.common.BookOuterClass.Books prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.common.Books}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.common.Books)
        com.grpc.common.BookOuterClass.BooksOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_Books_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_Books_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.common.BookOuterClass.Books.class, com.grpc.common.BookOuterClass.Books.Builder.class);
      }

      // Construct using com.grpc.common.BookOuterClass.Books.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBooksFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (booksBuilder_ == null) {
          books_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          booksBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_Books_descriptor;
      }

      @java.lang.Override
      public com.grpc.common.BookOuterClass.Books getDefaultInstanceForType() {
        return com.grpc.common.BookOuterClass.Books.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.common.BookOuterClass.Books build() {
        com.grpc.common.BookOuterClass.Books result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.common.BookOuterClass.Books buildPartial() {
        com.grpc.common.BookOuterClass.Books result = new com.grpc.common.BookOuterClass.Books(this);
        int from_bitField0_ = bitField0_;
        if (booksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            books_ = java.util.Collections.unmodifiableList(books_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.books_ = books_;
        } else {
          result.books_ = booksBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.common.BookOuterClass.Books) {
          return mergeFrom((com.grpc.common.BookOuterClass.Books)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.common.BookOuterClass.Books other) {
        if (other == com.grpc.common.BookOuterClass.Books.getDefaultInstance()) return this;
        if (booksBuilder_ == null) {
          if (!other.books_.isEmpty()) {
            if (books_.isEmpty()) {
              books_ = other.books_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBooksIsMutable();
              books_.addAll(other.books_);
            }
            onChanged();
          }
        } else {
          if (!other.books_.isEmpty()) {
            if (booksBuilder_.isEmpty()) {
              booksBuilder_.dispose();
              booksBuilder_ = null;
              books_ = other.books_;
              bitField0_ = (bitField0_ & ~0x00000001);
              booksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBooksFieldBuilder() : null;
            } else {
              booksBuilder_.addAllMessages(other.books_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.common.BookOuterClass.Books parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.common.BookOuterClass.Books) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.grpc.common.BookOuterClass.Book> books_ =
        java.util.Collections.emptyList();
      private void ensureBooksIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          books_ = new java.util.ArrayList<com.grpc.common.BookOuterClass.Book>(books_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.grpc.common.BookOuterClass.Book, com.grpc.common.BookOuterClass.Book.Builder, com.grpc.common.BookOuterClass.BookOrBuilder> booksBuilder_;

      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public java.util.List<com.grpc.common.BookOuterClass.Book> getBooksList() {
        if (booksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(books_);
        } else {
          return booksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public int getBooksCount() {
        if (booksBuilder_ == null) {
          return books_.size();
        } else {
          return booksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public com.grpc.common.BookOuterClass.Book getBooks(int index) {
        if (booksBuilder_ == null) {
          return books_.get(index);
        } else {
          return booksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public Builder setBooks(
          int index, com.grpc.common.BookOuterClass.Book value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.set(index, value);
          onChanged();
        } else {
          booksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public Builder setBooks(
          int index, com.grpc.common.BookOuterClass.Book.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.set(index, builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public Builder addBooks(com.grpc.common.BookOuterClass.Book value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.add(value);
          onChanged();
        } else {
          booksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public Builder addBooks(
          int index, com.grpc.common.BookOuterClass.Book value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.add(index, value);
          onChanged();
        } else {
          booksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public Builder addBooks(
          com.grpc.common.BookOuterClass.Book.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.add(builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public Builder addBooks(
          int index, com.grpc.common.BookOuterClass.Book.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.add(index, builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public Builder addAllBooks(
          java.lang.Iterable<? extends com.grpc.common.BookOuterClass.Book> values) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, books_);
          onChanged();
        } else {
          booksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public Builder clearBooks() {
        if (booksBuilder_ == null) {
          books_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          booksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public Builder removeBooks(int index) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.remove(index);
          onChanged();
        } else {
          booksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public com.grpc.common.BookOuterClass.Book.Builder getBooksBuilder(
          int index) {
        return getBooksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public com.grpc.common.BookOuterClass.BookOrBuilder getBooksOrBuilder(
          int index) {
        if (booksBuilder_ == null) {
          return books_.get(index);  } else {
          return booksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public java.util.List<? extends com.grpc.common.BookOuterClass.BookOrBuilder> 
           getBooksOrBuilderList() {
        if (booksBuilder_ != null) {
          return booksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(books_);
        }
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public com.grpc.common.BookOuterClass.Book.Builder addBooksBuilder() {
        return getBooksFieldBuilder().addBuilder(
            com.grpc.common.BookOuterClass.Book.getDefaultInstance());
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public com.grpc.common.BookOuterClass.Book.Builder addBooksBuilder(
          int index) {
        return getBooksFieldBuilder().addBuilder(
            index, com.grpc.common.BookOuterClass.Book.getDefaultInstance());
      }
      /**
       * <code>repeated .com.grpc.common.Book books = 1;</code>
       */
      public java.util.List<com.grpc.common.BookOuterClass.Book.Builder> 
           getBooksBuilderList() {
        return getBooksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.grpc.common.BookOuterClass.Book, com.grpc.common.BookOuterClass.Book.Builder, com.grpc.common.BookOuterClass.BookOrBuilder> 
          getBooksFieldBuilder() {
        if (booksBuilder_ == null) {
          booksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.grpc.common.BookOuterClass.Book, com.grpc.common.BookOuterClass.Book.Builder, com.grpc.common.BookOuterClass.BookOrBuilder>(
                  books_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          books_ = null;
        }
        return booksBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.common.Books)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.common.Books)
    private static final com.grpc.common.BookOuterClass.Books DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.common.BookOuterClass.Books();
    }

    public static com.grpc.common.BookOuterClass.Books getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Books>
        PARSER = new com.google.protobuf.AbstractParser<Books>() {
      @java.lang.Override
      public Books parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Books(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Books> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Books> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.common.BookOuterClass.Books getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BookIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.common.BookId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code com.grpc.common.BookId}
   */
  public  static final class BookId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.common.BookId)
      BookIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BookId.newBuilder() to construct.
    private BookId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BookId() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BookId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_BookId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_BookId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.common.BookOuterClass.BookId.class, com.grpc.common.BookOuterClass.BookId.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.common.BookOuterClass.BookId)) {
        return super.equals(obj);
      }
      com.grpc.common.BookOuterClass.BookId other = (com.grpc.common.BookOuterClass.BookId) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.common.BookOuterClass.BookId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.common.BookOuterClass.BookId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.BookId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.common.BookOuterClass.BookId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.BookId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.common.BookOuterClass.BookId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.BookId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.common.BookOuterClass.BookId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.BookId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.common.BookOuterClass.BookId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.common.BookOuterClass.BookId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.common.BookOuterClass.BookId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.common.BookOuterClass.BookId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.common.BookId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.common.BookId)
        com.grpc.common.BookOuterClass.BookIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_BookId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_BookId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.common.BookOuterClass.BookId.class, com.grpc.common.BookOuterClass.BookId.Builder.class);
      }

      // Construct using com.grpc.common.BookOuterClass.BookId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.common.BookOuterClass.internal_static_com_grpc_common_BookId_descriptor;
      }

      @java.lang.Override
      public com.grpc.common.BookOuterClass.BookId getDefaultInstanceForType() {
        return com.grpc.common.BookOuterClass.BookId.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.common.BookOuterClass.BookId build() {
        com.grpc.common.BookOuterClass.BookId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.common.BookOuterClass.BookId buildPartial() {
        com.grpc.common.BookOuterClass.BookId result = new com.grpc.common.BookOuterClass.BookId(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.common.BookOuterClass.BookId) {
          return mergeFrom((com.grpc.common.BookOuterClass.BookId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.common.BookOuterClass.BookId other) {
        if (other == com.grpc.common.BookOuterClass.BookId.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.common.BookOuterClass.BookId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.common.BookOuterClass.BookId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.common.BookId)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.common.BookId)
    private static final com.grpc.common.BookOuterClass.BookId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.common.BookOuterClass.BookId();
    }

    public static com.grpc.common.BookOuterClass.BookId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BookId>
        PARSER = new com.google.protobuf.AbstractParser<BookId>() {
      @java.lang.Override
      public BookId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BookId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BookId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.common.BookOuterClass.BookId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_common_Book_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_common_Book_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_common_Books_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_common_Books_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_common_BookId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_common_BookId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nBook.proto\022\017com.grpc.common\032\014Author.pr" +
      "oto\"u\n\004Book\022#\n\002id\030\001 \001(\0132\027.com.grpc.commo" +
      "n.BookId\022\014\n\004name\030\002 \001(\t\022\021\n\tpageCount\030\003 \001(" +
      "\005\022\'\n\006author\030\004 \001(\0132\027.com.grpc.common.Auth" +
      "or\"-\n\005Books\022$\n\005books\030\001 \003(\0132\025.com.grpc.co" +
      "mmon.Book\"\024\n\006BookId\022\n\n\002id\030\001 \001(\0052\217\001\n\014Book" +
      "Services\022<\n\010bookById\022\027.com.grpc.common.B" +
      "ookId\032\025.com.grpc.common.Book\"\000\022A\n\014findAl" +
      "lBooks\022\027.com.grpc.common.BookId\032\026.com.gr" +
      "pc.common.Books\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.grpc.common.AuthorOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_grpc_common_Book_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpc_common_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_common_Book_descriptor,
        new java.lang.String[] { "Id", "Name", "PageCount", "Author", });
    internal_static_com_grpc_common_Books_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpc_common_Books_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_common_Books_descriptor,
        new java.lang.String[] { "Books", });
    internal_static_com_grpc_common_BookId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_grpc_common_BookId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_common_BookId_descriptor,
        new java.lang.String[] { "Id", });
    com.grpc.common.AuthorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
